language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sohinipattanayak/react-docker-travis-beanstalk -f Dockerfile.dev .

script:
  - docker run -e CI=true sohinipattanayak/react-docker-travis-beanstalk npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker-travis-aws-beanstalk"
  env: "reactdockertravisawsbeanstalk-env"
  bucket_name: "elasticbeanstalk-us-east-1-517466900459"
  bucket_path: "react-docker-travis-aws-beanstalk"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
