language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sohinipattanayak/react-docker-travis-beanstalk -f Dockerfile.dev .

script:
  - docker run -e CI=true sohinipattanayak/react-docker-travis-beanstalk npm run test
